sudo: false
language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
    - nightly
    - "7.1"
    - "7.0"
    - "5.6"
    - "5.3"

env:
   - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

before_script:
  - bash bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - phpunit
