language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.9.1 WP_MULTISITE=0
    - WP_VERSION=3.9.1 WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1

notifications:
    secure: "WTJTZhNgvBhgR2x/r+6xuIwS3DspWMO3LX7u0Xn1JwYrVzFoK+nJKdP+fVjgVDAHYPkDK+75pdO7mEVaCBSZOe0D5lJQlCIzN69kY3zT59/m6KBYWj69c8Kk1imzd28qltC10fvAP9wMsQ6BsXj0ThGydm4mh5snK7Gt0uvnxB0="
    email: false

before_script:
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
