<?php
global $pagenow;


if ( $pagenow === 'user-edit.php' ) {
		$user              = 'this customer';
		$user_instructions = '<br><br><strong> Set this to -1<strong/> to prevent this customer from launching more sites';
} else {
		$user = 'a subscriber';
		$user_instructions = '';
}

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		[
			'key'                   => 'group_5afc7b8e22840',
			'title'                 => 'Dollie Access Settings',
			'fields'                => [
				[
				'key' => 'field_612616dc483456f24rnjgnjk64',
				'label' => dollie()->show_helper_video('product-setup', 'h3a5WqBTKQI', 'Watch Video', 'Custom Backups'),
				'name' => 'dollie_show_video',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'dollie-field-break',
					'id' => '',
				),
				'hide_admin' => 0,
				'message' => 'Below you can configure access & limits to all your Dollie Hub features. Watch the video to learn more.',
				'new_lines' => '',
				'esc_html' => 0,
				],
				[
					'key'               => 'field_5e2c1a97c1541',
					'label'             => __( 'Basic', 'dollie' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'placement'         => 'top',
					'endpoint'          => 0,
				],
				[
					'key'               => 'field_5afc7bad022a8',
					'label'             => __( 'Number of Sites', 'dollie' ),
					'name'              => '_wpd_installs',
					'type'              => 'number',
					'instructions'      => sprintf( esc_html__( 'How many sites can %s launch?', 'dollie' ), $user) . $user_instructions,
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'hide_admin'        => 0,
					'default_value'     => 1,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				],
				[
					'key'               => 'field_5afc7c0a022a9',
					'label'             => __( 'Disk Space', 'dollie' ),
					'name'              => '_wpd_max_size',
					'type'              => 'number',
					'instructions'      => sprintf( esc_html__( 'How much space can %s use for all their sites combined?',  'dollie'), $user),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'hide_admin'        => 0,
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => 'GB',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				],
				[
					'key' => 'field_60ace0aedf140',
					'label' => __('Staging Sites', 'dollie'),
					'name' => '_wpd_staging_installs',
					'type' => 'number',
					'instructions'      => sprintf( esc_html__( 'How many staging sites can %s launch?',  'dollie'), $user),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'hide_admin' => 0,
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				],
				[
					'key'               => 'field_5e2c1ac7c1542',
					'label'             => __( 'Blueprints', 'dollie' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'placement'         => 'top',
					'endpoint'          => 0,
				],
				[
					'key'               => 'field_5e2c1adcc1543',
					'label'             => __( 'Allowed Blueprints', 'dollie' ),
					'name'              => '_wpd_included_blueprints',
					'type'              => 'relationship',
					'instructions'      => sprintf( 'Select which of your Blueprints are <strong>allowed</strong> to be launched by %s',  $user),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'post_type'         => [
						0 => 'container',
					],
					'taxonomy'          => '',
					'filters'           => '',
					'elements'          => '',
					'min'               => '',
					'max'               => '',
					'return_format'     => 'id',
				],
				[
					'key'               => 'field_5e2c1b94c1544',
					'label'             => __( 'Disallowed Blueprints', 'dollie' ),
					'name'              => '_wpd_excluded_blueprints',
					'type'              => 'relationship',
					'instructions'     	=> sprintf( 'Select which of your Blueprints can <strong>not allowed</strong> by %s. Use this setting if you have a lot of blueprints and only want to restrict access to a couple of them.', $user),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'post_type'         => [
						0 => 'container',
					],
					'taxonomy'          => '',
					'filters'           => '',
					'elements'          => '',
					'min'               => '',
					'max'               => '',
					'return_format'     => 'id',
				],
				[
					'key' => 'field_5e2c1a97c154dkfky1',
					'label' => __( 'Site Management', 'dollie' ),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => [
					'width' => '',
					'class' => '',
					'id' => '',
					],
					'placement' => 'top',
					'endpoint' => 0,
				],
				array(
				'key' => 'field_5b094ea3fe6ea',
				'label' => sprintf(esc_html__('Enable %1$s Dashboard for %2$s', 'dollie-setup'), dollie()->string_variants()->get_site_type_string(), dollie()->string_variants()->get_user_type_plural_string()),
				'name' => 'wpd_allow_site_dashboard_access',
				'type' => 'true_false',
				'instructions' => sprintf(esc_html__('Would you like to give your %1$s the ability to manage their own %2$s or would you like to restrict this functionality to your team only?', 'dollie-setup'), dollie()->string_variants()->get_user_type_plural_string(), dollie()->string_variants()->get_site_type_plural_string()),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
				array(
				'key' => 'field_5b06c0124f11a',
				'label' => sprintf(esc_html__('%s Dashboard Features', 'dollie-setup'), dollie()->string_variants()->get_site_type_string()),
				'name' => 'available_sections',
				'type' => 'checkbox',
				'instructions' => sprintf(esc_html__('Depending on the type of %1$s you focus on, you can choose to disable certain (advanced) features of the %2$s Dashboard.', 'dollie-setup'), dollie()->string_variants()->get_user_type_plural_string(), dollie()->string_variants()->get_site_type_string()),
				'required' => 0,
				'conditional_logic' => array(
						array(
							array(
							'field' => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'dashboard' => 'Dashboard',
					'plugins' => 'Plugins',
					'themes' => 'Themes',
					'domains' => 'Domains',
					'migrate' => 'Migrate',
					'backups' => 'Backups',
					'updates' => 'Updates',
					'developer-tools' => 'Developer Tools',
					'delete' => 'Site Deletion',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => 'dashboard',
					1 => 'plugins',
					2 => 'themes',
					3 => 'domains',
					4 => 'migrate',
					5 => 'backups',
					6 => 'updates',
					7 => 'developer-tools',
					8 => 'domain',
					9 => 'delete',
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
				array(
				'key' => 'field_58861a3cc49b2',
				'label' => __('Available Developer Features', 'dollie'),
				'name' => 'available_features_developers',
				'type' => 'checkbox',
				'instructions' => sprintf(esc_html__('Disable certain (advanced) features of the %s Developer Tools.', 'dollie-setup'), dollie()->string_variants()->get_site_type_string()),
				'required' => 0,
				'conditional_logic' => array(
						array(
							array(
							'field' => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'code-editor' => 'Code Editor',
					'database' => 'Database',
					'shell' => 'WP-CLI',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => 'code-editor',
					1 => 'adminer',
					2 => 'shell',
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),


			],
			'location'              => [
				[
				[
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'dollie-access-groups',
				],
				],
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'product',
					],
				],
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'download',
					],
				],
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'memberpressproduct',
					],
				],
				[
					[
						'param'    => 'user_form',
						'operator' => '==',
						'value'    => 'edit',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		]
	);

endif;
