<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5e729a60cde61',
		'title' => '[Form] After Launch Wizard',
		'fields' => array(
			array(
				'key' => 'field_5e729d5994745',
				'label' => 'Page 1',
				'name' => '',
				'type' => 'page',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => true,
				'show_numbering' => 1,
				'previous_text' => '',
				'next_text' => '',
			),
			array(
				'key' => 'field_5e729cf629ee9',
				'label' => 'What would you like to do?',
				'name' => 'what_to_do',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'setup' => 'Continue setting up my new site',
					'migrate' => 'Migrate an existing WordPress site to this new install',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'setup',
				'layout' => 'vertical',
				'return_format' => 'array',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5e729ebfdbdc2',
				'label' => 'Page 2',
				'name' => '',
				'type' => 'page',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => true,
				'show_numbering' => 1,
				'previous_text' => '',
				'next_text' => '',
			),
			array(
				'key' => 'field_5e729de911000',
				'label' => 'Site Name',
				'name' => 'site_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'setup',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e72a094ba6a8',
				'label' => 'Site Description',
				'name' => 'site_description',
				'type' => 'text',
				'instructions' => 'Depending on your WordPress theme your description might be shown in several areas across your site. It\'s also shown in the visitors browser window title.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'setup',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e7363c04012a',
				'label' => 'Admin Email',
				'name' => 'admin_email',
				'type' => 'email',
				'instructions' => 'This address is used for admin purposes, like new user notifications. In most cases you probably want to use the same address you used when creating your account.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'setup',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5e72a0bbba6a9',
				'label' => 'Admin Username',
				'name' => 'admin_username',
				'type' => 'text',
				'instructions' => 'The username you use to login to your WordPress admin.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'setup',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e72a0f6ba6aa',
				'label' => 'Admin Password',
				'name' => 'admin_password',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'setup',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e7339f6f73f8',
				'label' => 'Migration Instructions',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'migrate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'message' => '{dollie_migration_instructions}',
				'new_lines' => '',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5e7348ccc4e8c',
				'label' => 'How did your migration go?',
				'name' => 'migration_status',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'migrate',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'great' => 'Great, It worked perfectly!',
					'issues' => 'The migration completed, but my site has issues',
					'failed' => 'The migration failed completely :-(',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5e7349b4c4e8e',
				'label' => 'Contact Support',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e729cf629ee9',
							'operator' => '==',
							'value' => 'migrate',
						),
						array(
							'field' => 'field_5e7348ccc4e8c',
							'operator' => '!=',
							'value' => 'great',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'message' => '<div class="box-light padding-half">
<h4>No worries , we\'re here to help!</h4>

Please create a support ticket so our team can assist you in completing your content migration.

</div>',
				'new_lines' => '',
				'esc_html' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'af_form',
					'operator' => '==',
					'value' => 'form_dollie_after_launch',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5e6a176c384ee',
		'title' => '[Form] Launch Site',
		'fields' => array(
			array(
				'key' => 'field_5e6a1773d54c4',
				'label' => 'Choose Your URL',
				'name' => 'site_url',
				'type' => 'text',
				'instructions' => 'Please choose a temporary URL for your site. This will be the place where you can work on your site used until you are ready to go live and connect your own domain.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5e6a1861b9025',
				'label' => 'Admin Email',
				'name' => 'site_admin_email',
				'type' => 'email',
				'instructions' => 'This is the email address you use to login to your WordPress admin.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'hidden',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5e6a221a065b8',
				'label' => 'Select a Blueprint (optional)',
				'name' => 'site_blueprint',
				'type' => 'radio',
				'instructions' => 'Carefully crafted site designs made by our team which you can use as a starting point for your new site.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'af_form',
					'operator' => '==',
					'value' => 'form_dollie_launch_site',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5e7255fadcb82',
		'title' => '[Form] List Site Backups',
		'fields' => array(
			array(
				'key' => 'field_5e72562baf79a',
				'label' => 'Available Backups',
				'name' => 'site_backup',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'array',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5e7256abaf79b',
				'label' => 'What would you like to restore?',
				'name' => 'what_to_restore',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'full' => 'Everything (Files & Database)',
					'files-only' => 'Files Only',
					'database-only' => 'Database Only',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'array',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e729515bb78b',
				'label' => 'You are about to restore your site',
				'name' => 'final_message',
				'type' => 'calculated',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'af_form',
					'operator' => '==',
					'value' => 'form_dollie_list_backups',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
