<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5affdcd76c8d1',
		'title' => 'Blueprints',
		'fields' => array(
			array(
				'key' => 'field_5affdce12d99a',
				'label' => __('Make this a Product Blueprint?', 'dollie'),
				'name' => 'wpd_is_blueprint',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5db6f0c97158f',
				'label' => __('Private Blueprint?', 'dollie'),
				'name' => 'wpd_private_blueprint',
				'type' => 'radio',
				'instructions' => __('Would you like to make this Blueprint only available to users with the admin role?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'no',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b05801b71f85',
				'label' => __('Blueprint Title', 'dollie'),
				'name' => 'wpd_installation_blueprint_title',
				'type' => 'text',
				'instructions' => __('This is shown when using the shortcode [dollie-blueprints] on your pages.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5affdce12d99a',
							'operator' => '==',
							'value' => 'yes',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b057871639a5',
				'label' => __('Blueprint Description', 'dollie'),
				'name' => 'wpd_installation_blueprint_description',
				'type' => 'textarea',
				'instructions' => __('This is shown when using the shortcode [dollie-blueprints] on your pages.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5affdce12d99a',
							'operator' => '==',
							'value' => 'yes',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 13,
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5b0578b4639a6',
				'label' => __('Link to Hosting Product', 'dollie'),
				'name' => 'wpd_installation_blueprint_hosting_product',
				'type' => 'relationship',
				'instructions' => __('By linking this blueprint directly to a hosting product you can enable one-click checkout + deployment for your new customers.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5affdce12d99a',
							'operator' => '==',
							'value' => 'yes',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'post_type' => array(
					0 => 'product',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'elements' => array(
					0 => 'featured_image',
				),
				'min' => '',
				'max' => 1,
				'return_format' => 'id',
			),
			array(
				'key' => 'field_5b07d0d9dac66',
				'label' => __('Blueprint Image', 'dollie'),
				'name' => 'wpd_blueprint_image',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'theme' => 'Active Theme Image (screenshot.png)',
					'screenshot' => 'Screenshot',
					'custom' => 'Custom',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5b07d123dac67',
				'label' => __('Upload Your Custom Image', 'dollie'),
				'name' => 'wpd_blueprint_custom_image',
				'type' => 'image',
				'instructions' => __('Ideal dimensions are 700 x 525 PX', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b07d0d9dac66',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => 1600,
				'max_height' => '',
				'max_size' => 1,
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'container',
				),
			),
		),
		'menu_order' => -2147483648,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5af9435f11e79',
		'title' => 'Management',
		'fields' => array(
			array(
				'key' => 'field_5af943727c113',
				'label' => __('Status', 'dollie'),
				'name' => 'wpd_container_status',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'start' => 'Active',
					'restart' => 'Restart',
					'stop' => 'Stopped',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'start',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5af9444e7c114',
				'label' => __('Notes', 'dollie'),
				'name' => 'wpd_container_notes',
				'type' => 'wysiwyg',
				'instructions' => __('Did something custom for this container? Leave notes here.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'container',
				),
			),
		),
		'menu_order' => -10,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5af8272e96d48',
		'title' => 'Container Details',
		'fields' => array(
			array(
				'key' => 'field_5af82852c985c',
				'label' => __('WP Details', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5af8273fc9855',
				'label' => __('Domain', 'dollie'),
				'name' => 'wpd_domains',
				'type' => 'text',
				'instructions' => __('The domain connected to this container.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af82a78c9860',
				'label' => __('WordPress Version', 'dollie'),
				'name' => 'wpd_installation_version',
				'type' => 'text',
				'instructions' => __('The domain connected to this container.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af82785c9856',
				'label' => __('Site Name', 'dollie'),
				'name' => 'wpd_installation_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af827e4c9857',
				'label' => __('Registered Users', 'dollie'),
				'name' => 'wpd_installation_users',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af827f4c9858',
				'label' => __('WP Admin Email', 'dollie'),
				'name' => 'wpd_installation_admin_email',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af8280cc9859',
				'label' => __('Active Theme', 'dollie'),
				'name' => 'wpd_installation_themes',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af82814c985a',
				'label' => __('Installation Size', 'dollie'),
				'name' => 'wpd_installation_size',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af82a62c985f',
				'label' => __('Email Sent', 'dollie'),
				'name' => 'wpd_installation_emails_sent',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af8281fc985b',
				'label' => __('Management', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5af8286dc985d',
				'label' => __('Connected to Dollie API?', 'dollie'),
				'name' => 'wpd_node_added',
				'type' => 'text',
				'instructions' => __('Remove the \'yes\' value to re-register this container with the Dollie Management API. You\'d only want to do this if there are issues with sending commands to this container (for example switching PHP versions or restoring from backups).', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af82983c985e',
				'label' => __('Site Setup Complete?', 'dollie'),
				'name' => 'wpd_setup_complete',
				'type' => 'text',
				'instructions' => __('Remove the \'yes\' value if you (or your customer) wants to go through the initial site setup/migration again.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af9969177474',
				'label' => __('Blueprint Setup Complete', 'dollie'),
				'name' => 'wpd_demo_complete',
				'type' => 'text',
				'instructions' => __('If this site is based on a blueprint remove this value if you\'d like to setup the blueprint again.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5af82c9c2c40a',
				'label' => __('Backups Available', 'dollie'),
				'name' => 'wpd_installation_backups_available',
				'type' => 'text',
				'instructions' => __('The total amount of backups made.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'container',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5ada1549129fb',
		'title' => 'Dollie',
		'fields' => array(
			array(
				'key' => 'field_5adc6aca0a0b4',
				'label' => __('Core', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5e2eb1ca86e3d',
				'label' => __('Charge For Launching Sites?', 'dollie'),
				'name' => 'wpd_charge_for_deployments',
				'type' => 'true_false',
				'instructions' => __('Would you like to charge your customers for launching websites? If you have this set to "off" anyone can launch sites on your platform without having a paid (WooCommerce) subscription.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'On',
				'ui_off_text' => 'Off',
			),
			array(
				'key' => 'field_5e2eb1ca86e3c',
				'label' => __('Status', 'dollie'),
				'name' => 'wpd_dollie_status',
				'type' => 'true_false',
				'instructions' => __('In staging you can test out Dollie as long as you\'d like. <br>Ready to go live with Dollie? Make sure you have completed the <a href="https://partners.getdollie.com/go-live" target="_blank" >partner onboarding process </a> and our white glove onboarding team will provide you with the right settings. <br><strong>Making changes to these settings before you\'ve gone live will lead to failed deployments.</strong>', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Live',
				'ui_off_text' => 'Staging',
			),
			array(
				'key' => 'field_5cf62cee6f366',
				'label' => __('Your Deployment Domain', 'dollie'),
				'name' => 'wpd_api_domain',
				'type' => 'url',
				'instructions' => __('Which domain are you using for the sites deployed by you or your customers? Make sure you have connected your custom domain by following the video: <a href="https://www.youtube.com/watch?v=1yoUr19iUR4&feature=youtu.be target="_blank"">Connecting Your Own Domain</a>', 'dollie'),
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e2eb1ca86e3c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'dollie.io',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5ada182522c80',
				'label' => __('Dollie Console URL', 'dollie'),
				'name' => 'wpd_api_dashboard_url',
				'type' => 'url',
				'instructions' => __('The unique URL to your Dollie Console. This is usually something like <yourpartnername-cp.dollie.io> but you might have customized it, so make sure to double check. See:
<a href="https://youtu.be/1EwJkrJp2-Q" target="_blank"">Setting up API access</a>', 'dollie'),
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e2eb1ca86e3c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5ada15d5bc584',
				'label' => __('Dollie API Email', 'dollie'),
				'name' => 'wpd_api_email',
				'type' => 'text',
				'instructions' => __('During the partner onboarding you have created your unique API connection details that you need to fill in here. See:
<a href="https://youtu.be/1EwJkrJp2-Q" target="_blank"">Setting up API access</a>', 'dollie'),
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e2eb1ca86e3c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ada1676bc585',
				'label' => __('Dollie API Password', 'dollie'),
				'name' => 'wpd_api_password',
				'type' => 'password',
				'instructions' => __('During the partner onboarding you have created your unique API connection details that you need to fill in here. See:
<a href="https://youtu.be/1EwJkrJp2-Q" target="_blank"">Setting up API access</a>', 'dollie'),
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5e2eb1ca86e3c',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5e5557cda4c7b',
				'label' => __('Pages', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5e5557eda4c7c',
				'label' => __('Launch Site Page', 'dollie'),
				'name' => 'wpd_launch_page_id',
				'type' => 'post_object',
				'instructions' => __('From which page do your customers launch their sites?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'field_5e555885a4c7e',
				'label' => __('Customer Dashboard Page', 'dollie'),
				'name' => 'wpd_dashboard_page_id',
				'type' => 'post_object',
				'instructions' => __('From which page do your customers launch their sites?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'field_5e555864a4c7d',
				'label' => __('Customer Login Page', 'dollie'),
				'name' => 'wpd_login_page_id',
				'type' => 'post_object',
				'instructions' => __('From which page do your customers launch their sites?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'page',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'field_5e9835e40bfb6',
				'label' => __('Support Link', 'dollie'),
				'name' => 'wpd_support_link',
				'type' => 'url',
				'instructions' => __('This is the URL we use when directing users to submit a ticket for support.', 'dollie'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5adc6af60a0b5',
				'label' => __('Branding', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5adc7193ac968',
				'label' => __('Dashboard Logo', 'dollie'),
				'name' => 'wpd_dashboard_logo',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5afd4d2021885',
				'label' => __('Dashboard Logo Inversed', 'dollie'),
				'name' => 'wpd_dashboard_logo_inversed',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5adc6e0a0a0b8',
				'label' => __('Header Style', 'dollie'),
				'name' => 'wpd_header_style',
				'type' => 'radio',
				'instructions' => __('Choose a pre-designed theme you\'d like to use', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'glass-inverse' => 'Default',
					'modern' => 'Elegance',
					'inverse' => 'Inverse',
					'glass' => 'Glass',
				),
				'allow_null' => 1,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'glass-inverse',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5adc6ce10a0b7',
				'label' => __('Sidebar Style', 'dollie'),
				'name' => 'wpd_sidebar_style',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Inversed Sidebar',
				'ui_off_text' => 'Regular Sidebar',
			),
			array(
				'key' => 'field_5adc6b010a0b6',
				'label' => __('Theme Preset', 'dollie'),
				'name' => 'wpd_theme',
				'type' => 'radio',
				'instructions' => __('Choose a pre-designed theme you\'d like to use', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Default',
					'elegance' => 'Elegance',
					'pulse' => 'Pulse',
					'flat' => 'Flat',
					'corporate' => 'Corporate',
					'earth' => 'Earth',
				),
				'allow_null' => 1,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_583b2f85ff318',
				'label' => __('Brand Color', 'dollie'),
				'name' => 'brand_color',
				'type' => 'color_picker',
				'instructions' => __('You can set a branding color that fits your business or product.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#4CA2BA',
			),
			array(
				'key' => 'field_5adf1b015c888',
				'label' => __('Newsfeed URL', 'dollie'),
				'name' => 'wpd_feed_url',
				'type' => 'url',
				'instructions' => __('The link to the WordPress installation you want to show news from.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'https://yoursite.com',
			),
			array(
				'key' => 'field_583b2eeaf884d',
				'label' => __('Default Screenshot Placeholder', 'dollie'),
				'name' => 'default_screenshot',
				'type' => 'image',
				'instructions' => __('<strong>Recommended size: 1200x900px</strong><br>
This is the default screenshot image shown on the site details header. It is only shown when the site owner has not set up their site yet.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_583b39c4b0648',
				'label' => __('Header Background Image', 'dollie'),
				'name' => 'site_details_bg',
				'type' => 'image',
				'instructions' => __('This is the default background image shown inside the headers. We recommend to upload a scalable SVG pattern', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'png, jpg,svg',
			),
			array(
				'key' => 'field_5db808224473a',
				'label' => __('Launch Site Wizard', 'dollie'),
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_5db73a6b5ba07',
				'label' => __('Step 1', 'dollie'),
				'name' => 'wpd_launch_step_1',
				'type' => 'wysiwyg',
				'instructions' => __('This is the first screen shown as soon as someone presses the "Launch Site" button.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '<h4 class="mt-0"><i class="fab fa-docker"></i> Launching New Cloud Container <span class="dots"></span></h4>
												<p> We use state-of-the-art technology like PHP7, Nginx, Redis, Memcached and MariaDB inside isolated cloud containers to guarantee excellent performance and security for each and every site we host.</p>',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_5db73b99d3b4b',
				'label' => __('Step 2', 'dollie'),
				'name' => 'wpd_launch_step_2',
				'type' => 'wysiwyg',
				'instructions' => __('This is the second screen shown as soon as someone presses the "Launch Site" button.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '<h4 class="mt-0"><i class="fab fa-wordpress-simple"></i> Setting up WordPress <span class="dots"></span></h4>
<p>We manage important WordPress security updates for you, and notify you when compromised plugins and themes with security issues are found. And of course free SSL certificates for your site are set up automatically..</p>',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_5db73bf2d3b4c',
				'label' => __('Step 3', 'dollie'),
				'name' => 'wpd_launch_step_3',
				'type' => 'wysiwyg',
				'instructions' => __('This is the third screen shown as soon as someone presses the "Launch Site" button.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '<h4 class="mt-0"><i class="fal fa-gem"></i> Testing & Verifying Installation<span class="dots"></span></h4>
												<p>
												 We\'re running some automated tests to make sure everything is set up and ready to go before you start building your brand new site!
												</p>
										</div>',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_5db808cb4473b',
				'label' => __('Step 4', 'dollie'),
				'name' => 'wpd_launch_step_4',
				'type' => 'wysiwyg',
				'instructions' => __('This is the final screen shown as soon as someone presses the "Launch Site" button. This only shows if the site deploy takes longer than usual.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '<h4 class="mt-0"><i class="fal fa-box-check"></i> Site Setup Complete <span class="dots"></span></h4>
							<p>
								Your new site Wordpress site is deployed to our cloud! You\'ll be redirected to the site setup wizard in just a couple of seconds...
							</p>',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_5b06a979537b3',
				'label' => __('Access Control', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b094ea3fe6ea',
				'label' => __('Enable Site Management Access?', 'dollie'),
				'name' => 'wpd_allow_site_dashboard_access',
				'type' => 'true_false',
				'instructions' => __('Would you like to give your clients/customers the ability to manage their own sites or would you like to restrict this functionality to your team (Administrators) only?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
			array(
				'key' => 'field_5b06c0124f11a',
				'label' => __('Available Site Management Features', 'dollie'),
				'name' => 'available_sections',
				'type' => 'checkbox',
				'instructions' => __('Depending on the customers you bring in, you can choose to disable certain sections of the customer dashboard.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'dashboard' => 'Dashboard',
					'backups' => 'Backups',
					'updates' => 'Updates',
					'developers' => 'Developer Tools',
					'blueprint' => 'Blueprints',
					'domain' => 'Domains',
					'delete-site' => 'Site Deletion',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => 'dashboard',
					1 => 'backups',
					2 => 'updates',
					3 => 'developers',
					4 => 'blueprint',
					5 => 'domain',
					6 => 'delete-site',
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'array',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_583b2ff20aaad',
				'label' => __('Available Site Management Tabs', 'dollie'),
				'name' => 'available_features',
				'type' => 'checkbox',
				'instructions' => __('Depending on the customers you bring in, you can choose to disable certain sections of the customer dashboard.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'plugins' => 'Plugins',
					'themes' => 'Themes',
					'emails' => 'Emails',
					'domains' => 'Domains',
					'cloudflare' => 'CloudFlare',
					'recommendations' => 'Recommendations',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
					0 => 'plugins',
					1 => 'themes',
					2 => 'emails',
					3 => 'domains',
					4 => 'cloudflare',
					5 => 'recommendations',
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'array',
			),
			array(
				'key' => 'field_58861a3cc49b2',
				'label' => __('Available Developer Tabs', 'dollie'),
				'name' => 'available_features_developers',
				'type' => 'checkbox',
				'instructions' => __('Depending on the customers you bring in, you can choose to disable certain sections of the developer dashboard.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'codiad' => 'Code Editor',
					'adminer' => 'Database',
					'shell' => 'WP-CLI',
					'performance' => 'Performance',
					'cloudflare' => 'CloudFlare',
					'php-debug' => 'WP Debug',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
					0 => 'codiad',
					1 => 'adminer',
					2 => 'shell',
					3 => 'performance',
					4 => 'cloudflare',
					5 => 'tools',
					6 => 'php-debug',
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'array',
			),
			array(
				'key' => 'field_5efc4a49d5752',
				'label' => __('Client Deployed Site Permissions', 'dollie'),
				'name' => 'wpd_client_site_permission',
				'type' => 'radio',
				'instructions' => __('Choose the user role given to the users when deploying a site. Warning, this will change the user roles for all client sites', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'administrator' => 'Administrator',
					'editor' => 'Editor',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'administrator',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5efc4ac9d5754',
				'label' => __('Administrator User Name', 'dollie'),
				'name' => 'wpd_admin_user_name',
				'type' => 'text',
				'instructions' => __('Choose the username that is created for your own administration access. This won\'t be shared with the client.', 'dollie'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5efc4a49d5752',
							'operator' => '==',
							'value' => 'editor',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => 's_admin',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b094d86fe6e8',
				'label' => __('Blueprints', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b097b1dd50cc',
				'label' => __('Enable Site Preview', 'dollie'),
				'name' => 'wpd_enable_site_preview',
				'type' => 'true_false',
				'instructions' => __('The site preview bar allows you to quickly showcase the available Blueprints you\'ve created. If you\'d like to enable this feature make sure you\'ve uploaded the Site Preview script to your root directory.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
			array(
				'key' => 'field_5b094db7fe6e9',
				'label' => __('Site Preview Link', 'dollie'),
				'name' => 'wpd_site_preview_path',
				'type' => 'text',
				'instructions' => __('The link to where your sites preview will show. By default is set to "preview" and will look like your-site.com/preview', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => 'preview',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5f561b0fc0227',
				'label' => __('Show Default Blueprint', 'dollie'),
				'name' => 'wpd_show_default_blueprint',
				'type' => 'true_false',
				'instructions' => __('When launching a new site, show or hide the Default Blueprint option.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5cb5cca213aae',
				'label' => __('Email Delivery', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5cb5cccd13aaf',
				'label' => __('Email Delivery Address', 'dollie'),
				'name' => 'wpd_delivery_email',
				'type' => 'text',
				'instructions' => __('The default transactional email address that\'s being used by the WordPress installation of your customers. Make sure this is properly set up and tested with SendGrid.', 'dollie'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'notifications@yourdomain.com',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cb5cee44bc8e',
				'label' => __('SMTP Host', 'dollie'),
				'name' => 'wpd_delivery_smtp_host',
				'type' => 'text',
				'instructions' => __('The default transactional email address that\'s being used by the WordPress installation of your customers. Make sure this is properly set up and tested with SendGrid.', 'dollie'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'smtp.sendgrid.net',
				'placeholder' => 'smtp.sendgrid.net',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cb5cd6013ab0',
				'label' => __('SMTP Port', 'dollie'),
				'name' => 'wpd_delivery_smtp',
				'type' => 'text',
				'instructions' => __('The port being used for SMTP delivery.', 'dollie'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 2525,
				'placeholder' => 'notifications@yourdomain.com',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cb5cd9413ab1',
				'label' => __('SendGrid Username', 'dollie'),
				'name' => 'wpd_delivery_username',
				'type' => 'text',
				'instructions' => __('Your SendGrid username', 'dollie'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5cb5cda513ab2',
				'label' => __('API Key / Password', 'dollie'),
				'name' => 'wpd_delivery_password',
				'type' => 'password',
				'instructions' => __('The password belonging to your SendGrid API account.', 'dollie'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'wpd_platform_setup',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5b0ea59dbbb22',
		'title' => 'Dollie Customer Data(do not edit)',
		'fields' => array(
			array(
				'key' => 'field_5b0ea5c46ffbb',
				'label' => __('Active Dollie Subscription', 'dollie'),
				'name' => 'wpd_active_subscription',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b0eaaa52ec57',
				'label' => __('Stop Container at..', 'dollie'),
				'name' => 'wpd_stop_container_at',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5b0eacb73940a',
				'label' => __('Containers undeployed?', 'dollie'),
				'name' => 'wpd_all_containers_undeployed',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'user_form',
					'operator' => '==',
					'value' => 'edit',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5efc4bbc3849b',
		'title' => 'Dollie Customer Info',
		'fields' => array(
			array(
				'key' => 'field_5efc4bbc3d814',
				'label' => __('Client Deployed Site Permissions', 'dollie'),
				'name' => 'wpd_client_site_permissions',
				'type' => 'button_group',
				'instructions' => __('Choose the user role given to the user when deploying a site. Default inherits from Dollie - Settings - Access Control', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'choices' => array(
					'default' => 'Default Dollie Setting',
					'administrator' => 'Administrator',
					'editor' => 'Editor',
				),
				'allow_null' => 0,
				'default_value' => 'default',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'user_form',
					'operator' => '==',
					'value' => 'edit',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5afc7b8e22840',
		'title' => 'Dollie Product Setup',
		'fields' => array(
			array(
				'key' => 'field_5e2c1a97c1541',
				'label' => __('Basic', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5afc7bad022a8',
				'label' => __('Number of Sites', 'dollie'),
				'name' => '_wpd_installs',
				'type' => 'number',
				'instructions' => __('How many sites can a customer deploy when subscribed to this product?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'hide_admin' => 0,
				'default_value' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5afc7c0a022a9',
				'label' => __('Disk Space', 'dollie'),
				'name' => '_wpd_max_size',
				'type' => 'number',
				'instructions' => __('How many sites can a customer deploy when subscribed to this product?', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 2,
				'prepend' => '',
				'append' => 'GB',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_5e2c1ac7c1542',
				'label' => __('Blueprints', 'dollie'),
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5e2c1adcc1543',
				'label' => __('Included Blueprints', 'dollie'),
				'name' => '_wpd_included_blueprints',
				'type' => 'relationship',
				'instructions' => __('Select which of your Blueprints are allowed to be deployed when a customer has an active subscription to this product.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'container',
				),
				'taxonomy' => '',
				'filters' => '',
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'field_5e2c1b94c1544',
				'label' => __('Excluded Blueprints', 'dollie'),
				'name' => '_wpd_excluded_blueprints',
				'type' => 'relationship',
				'instructions' => __('Select which of your Blueprints can not be chosen when a customer has an active subscription to this product. Use this setting if you have a lot of blueprints and only want to restrict access to a couple of them.', 'dollie'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'container',
				),
				'taxonomy' => '',
				'filters' => '',
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
