<?php
if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_5affdcd76c8d1',
		'title'                 => 'Blueprints',
		'fields'                => array(
			array(
				'key'               => 'field_5affdce12d99a',
				'label'             => __( 'Make this a Product Blueprint?', 'dollie' ),
				'name'              => 'wpd_is_blueprint',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
					'no'  => 'No',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'save_other_choice' => 0,
				'default_value'     => '',
				'layout'            => 'vertical',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_5db6f0c97158f',
				'label'             => __( 'Private Blueprint?', 'dollie' ),
				'name'              => 'wpd_private_blueprint',
				'type'              => 'radio',
				'instructions'      => __( 'Would you like to make this Blueprint only available to users with the admin role?', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'yes' => 'Yes',
					'no'  => 'No',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'default_value'     => 'no',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_5b05801b71f85',
				'label'             => __( 'Blueprint Title', 'dollie' ),
				'name'              => 'wpd_installation_blueprint_title',
				'type'              => 'text',
				'instructions'      => __( 'This is shown when using the shortcode [dollie-blueprints] on your pages.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5affdce12d99a',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5b057871639a5',
				'label'             => __( 'Blueprint Description', 'dollie' ),
				'name'              => 'wpd_installation_blueprint_description',
				'type'              => 'textarea',
				'instructions'      => __( 'This is shown when using the shortcode [dollie-blueprints] on your pages.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5affdce12d99a',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 13,
				'new_lines'         => 'wpautop',
			),
			array(
				'key'               => 'field_5b0578b4639a6',
				'label'             => __( 'Link to Hosting Product', 'dollie' ),
				'name'              => 'wpd_installation_blueprint_hosting_product',
				'type'              => 'relationship',
				'instructions'      => __( 'By linking this blueprint directly to a hosting product you can enable one-click checkout + deployment for your new customers.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5affdce12d99a',
							'operator' => '==',
							'value'    => 'yes',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'post_type'         => array(
					0 => 'product',
				),
				'taxonomy'          => '',
				'filters'           => array(
					0 => 'search',
					1 => 'taxonomy',
				),
				'elements'          => array(
					0 => 'featured_image',
				),
				'min'               => '',
				'max'               => 1,
				'return_format'     => 'id',
			),
			array(
				'key'               => 'field_5b07d0d9dac66',
				'label'             => __( 'Blueprint Image', 'dollie' ),
				'name'              => 'wpd_blueprint_image',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'theme'      => 'Active Theme Image (screenshot.png)',
					'screenshot' => 'Screenshot',
					'custom'     => 'Custom',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'save_other_choice' => 0,
				'default_value'     => '',
				'layout'            => 'horizontal',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_5b07d123dac67',
				'label'             => __( 'Upload Your Custom Image', 'dollie' ),
				'name'              => 'wpd_blueprint_custom_image',
				'type'              => 'image',
				'instructions'      => __( 'Ideal dimensions are 700 x 525 PX', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5b07d0d9dac66',
							'operator' => '==',
							'value'    => 'custom',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'url',
				'preview_size'      => 'thumbnail',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => 1600,
				'max_height'        => '',
				'max_size'          => 1,
				'mime_types'        => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'container',
				),
			),
		),
		'menu_order'            => - 2147483648,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5af9435f11e79',
		'title'                 => 'Management',
		'fields'                => array(
			array(
				'key'               => 'field_5af943727c113',
				'label'             => __( 'Status', 'dollie' ),
				'name'              => 'wpd_container_status',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'start'   => 'Active',
					'restart' => 'Restart',
					'stop'    => 'Stopped',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'save_other_choice' => 0,
				'default_value'     => 'start',
				'layout'            => 'vertical',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_5af9444e7c114',
				'label'             => __( 'Notes', 'dollie' ),
				'name'              => 'wpd_container_notes',
				'type'              => 'wysiwyg',
				'instructions'      => __( 'Did something custom for this container? Leave notes here.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 0,
				'delay'             => 1,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'container',
				),
			),
		),
		'menu_order'            => - 10,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5af8272e96d48',
		'title'                 => 'Container Details',
		'fields'                => array(
			array(
				'key'               => 'field_5af82852c985c',
				'label'             => __( 'WP Details', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5af8273fc9855',
				'label'             => __( 'Domain', 'dollie' ),
				'name'              => 'wpd_domains',
				'type'              => 'text',
				'instructions'      => __( 'The domain connected to this container.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af82a78c9860',
				'label'             => __( 'WordPress Version', 'dollie' ),
				'name'              => 'wpd_installation_version',
				'type'              => 'text',
				'instructions'      => __( 'The domain connected to this container.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af82785c9856',
				'label'             => __( 'Site Name', 'dollie' ),
				'name'              => 'wpd_installation_name',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af827e4c9857',
				'label'             => __( 'Registered Users', 'dollie' ),
				'name'              => 'wpd_installation_users',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af827f4c9858',
				'label'             => __( 'WP Admin Email', 'dollie' ),
				'name'              => 'wpd_installation_admin_email',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af8280cc9859',
				'label'             => __( 'Active Theme', 'dollie' ),
				'name'              => 'wpd_installation_themes',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af82814c985a',
				'label'             => __( 'Installation Size', 'dollie' ),
				'name'              => 'wpd_installation_size',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af82a62c985f',
				'label'             => __( 'Email Sent', 'dollie' ),
				'name'              => 'wpd_installation_emails_sent',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af8281fc985b',
				'label'             => __( 'Management', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5af8286dc985d',
				'label'             => __( 'Connected to Dollie API?', 'dollie' ),
				'name'              => 'wpd_node_added',
				'type'              => 'text',
				'instructions'      => __( 'Remove the \'yes\' value to re-register this container with the Dollie Management API. You\'d only want to do this if there are issues with sending commands to this container (for example switching PHP versions or restoring from backups).', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af82983c985e',
				'label'             => __( 'Site Setup Complete?', 'dollie' ),
				'name'              => 'wpd_setup_complete',
				'type'              => 'text',
				'instructions'      => __( 'Remove the \'yes\' value if you (or your customer) wants to go through the initial site setup/migration again.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af9969177474',
				'label'             => __( 'Blueprint Setup Complete', 'dollie' ),
				'name'              => 'wpd_demo_complete',
				'type'              => 'text',
				'instructions'      => __( 'If this site is based on a blueprint remove this value if you\'d like to setup the blueprint again.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5af82c9c2c40a',
				'label'             => __( 'Backups Available', 'dollie' ),
				'name'              => 'wpd_installation_backups_available',
				'type'              => 'text',
				'instructions'      => __( 'The total amount of backups made.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'container',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5ada1549129fb',
		'title'                 => 'Dollie',
		'fields'                => array(
			array(
				'key'               => 'field_5adc6aca0a0b4',
				'label'             => __( 'Core', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5cf62cee6f366',
				'label'             => __( 'Deployment Domain', 'dollie' ),
				'name'              => 'wpd_api_domain',
				'type'              => 'text',
				'instructions'      => __( 'Default domain you are using for the sites deployed by you or your customers. You can add below your own custom domain.', 'dollie' ),
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 1,
			),
			array(
				'key'               => 'field_5fc8d451c30aa',
				'label'             => __( 'Custom Deployment Domain', 'dollie' ),
				'name'              => 'wpd_api_domain_custom',
				'type'              => 'text',
				'instructions'      => __( 'Add a custom domain for site deployments. An unused domain is recommended.<br>
Dollie will handle all the DNS functionality for your deployed sites so you first need to change your NS entries at your domain registrar.<br>
NS entries: <strong>pdns1.stratus5.com</strong>, <strong>pdns2.stratus5.com</strong> and <strong>pdns3.stratus5.com</strong>', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5cf62cee6f366',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => '',
				'placeholder'       => 'example.com',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5e5557cda4c7b',
				'label'             => __( 'Pages', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5e5557eda4c7c',
				'label'             => __( 'Launch Site Page', 'dollie' ),
				'name'              => 'wpd_launch_page_id',
				'type'              => 'post_object',
				'instructions'      => __( 'From which page do your customers launch their sites?', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array(
					0 => 'page',
				),
				'taxonomy'          => '',
				'allow_null'        => 0,
				'multiple'          => 0,
				'return_format'     => 'id',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_5e555885a4c7e',
				'label'             => __( 'Customer Dashboard Page', 'dollie' ),
				'name'              => 'wpd_dashboard_page_id',
				'type'              => 'post_object',
				'instructions'      => __( 'From which page do your customers launch their sites?', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array(
					0 => 'page',
				),
				'taxonomy'          => '',
				'allow_null'        => 0,
				'multiple'          => 0,
				'return_format'     => 'id',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_5e555864a4c7d',
				'label'             => __( 'Customer Login Page', 'dollie' ),
				'name'              => 'wpd_login_page_id',
				'type'              => 'post_object',
				'instructions'      => __( 'From which page do your customers launch their sites?', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array(
					0 => 'page',
				),
				'taxonomy'          => '',
				'allow_null'        => 0,
				'multiple'          => 0,
				'return_format'     => 'id',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_5f671253a7256',
				'label'             => __( 'Sites Page', 'dollie' ),
				'name'              => 'wpd_sites_page_id',
				'type'              => 'post_object',
				'instructions'      => __( 'Choose the page where all the customers sites are listed.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'post_type'         => array(
					0 => 'page',
				),
				'taxonomy'          => '',
				'allow_null'        => 0,
				'multiple'          => 0,
				'return_format'     => 'id',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_5f67107253906',
				'label'             => __( 'Site Template', 'dollie' ),
				'name'              => 'wpd_site_template_id',
				'type'              => 'post_object',
				'instructions'      => __( 'Choose the Elementor template for your site page.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'post_type'         => array(
					0 => 'elementor_library',
				),
				'taxonomy'          => array(
					0 => 'elementor_library_type:dollie-templates',
				),
				'allow_null'        => 0,
				'multiple'          => 0,
				'return_format'     => 'id',
				'ui'                => 1,
			),
			array(
				'key'               => 'field_5e9835e40bfb6',
				'label'             => __( 'Support Link', 'dollie' ),
				'name'              => 'wpd_support_link',
				'type'              => 'url',
				'instructions'      => __( 'This is the URL we use when directing users to submit a ticket for support.', 'dollie' ),
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => '',
				'placeholder'       => 'https://yoursite.com',
			),
			array(
				'key'               => 'field_5adc6af60a0b5',
				'label'             => __( 'Branding', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5adf1b015c888',
				'label'             => __( 'Newsfeed URL', 'dollie' ),
				'name'              => 'wpd_feed_url',
				'type'              => 'url',
				'instructions'      => __( 'The link to the WordPress installation you want to show news from.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => 'https://getdollie.com',
				'placeholder'       => 'https://yoursite.com',
			),
			array(
				'key'               => 'field_583b2eeaf884d',
				'label'             => __( 'Default Screenshot Placeholder', 'dollie' ),
				'name'              => 'default_screenshot',
				'type'              => 'image',
				'instructions'      => __( '<strong>Recommended size: 700x460px</strong><br>
This is the default screenshot image shown until a live screenshot is generated.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'return_format'     => 'url',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5b06a979537b3',
				'label'             => __( 'Access Control', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5e2eb1ca86e3d',
				'label'             => __( 'Charge For Launching Sites?', 'dollie' ),
				'name'              => 'wpd_charge_for_deployments',
				'type'              => 'true_false',
				'instructions'      => __( 'Would you like to charge your customers for launching websites? If you have this set to "off" anyone can launch sites on your platform without having a paid (WooCommerce) subscription.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 1,
				'ui'                => 1,
				'ui_on_text'        => 'On',
				'ui_off_text'       => 'Off',
			),
			array(
				'key'               => 'field_5b094ea3fe6ea',
				'label'             => __( 'Enable Site Management Access?', 'dollie' ),
				'name'              => 'wpd_allow_site_dashboard_access',
				'type'              => 'true_false',
				'instructions'      => __( 'Would you like to give your clients/customers the ability to manage their own sites or would you like to restrict this functionality to your team (Administrators) only?', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 1,
				'ui'                => 1,
				'ui_on_text'        => 'Yes',
				'ui_off_text'       => 'No',
			),
			array(
				'key'               => 'field_5b06c0124f11a',
				'label'             => __( 'Available Site Management Features', 'dollie' ),
				'name'              => 'available_sections',
				'type'              => 'checkbox',
				'instructions'      => __( 'Depending on the customers you bring in, you can choose to disable certain sections of the customer dashboard.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'choices'           => array(
					'dashboard'       => 'Dashboard',
					'plugins'         => 'Plugins',
					'themes'          => 'Themes',
					'domains'         => 'Domains',
					'migrate'         => 'Migrate',
					'backups'         => 'Backups',
					'updates'         => 'Updates',
					'developer-tools' => 'Developer Tools',
					'blueprints'      => 'Blueprints',
					'delete'          => 'Site Deletion',
				),
				'allow_custom'      => 0,
				'default_value'     => array(
					0  => 'dashboard',
					1  => 'plugins',
					2  => 'themes',
					3  => 'domains',
					4  => 'migrate',
					5  => 'backups',
					6  => 'updates',
					7  => 'developer-tools',
					8  => 'blueprints',
					9  => 'domain',
					10 => 'delete',
				),
				'layout'            => 'vertical',
				'toggle'            => 0,
				'return_format'     => 'value',
				'save_custom'       => 0,
			),
			array(
				'key'               => 'field_58861a3cc49b2',
				'label'             => __( 'Available Developer Tabs', 'dollie' ),
				'name'              => 'available_features_developers',
				'type'              => 'checkbox',
				'instructions'      => __( 'Depending on the customers you bring in, you can choose to disable certain sections of the developer dashboard.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5b094ea3fe6ea',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'choices'           => array(
					'code-editor' => 'Code Editor',
					'database'    => 'Database',
					'shell'       => 'WP-CLI',
				),
				'allow_custom'      => 0,
				'default_value'     => array(
					0 => 'code-editor',
					1 => 'adminer',
					2 => 'shell',
				),
				'layout'            => 'vertical',
				'toggle'            => 0,
				'return_format'     => 'value',
				'save_custom'       => 0,
			),
			array(
				'key'               => 'field_5efc4a49d5752',
				'label'             => __( 'Client Deployed Site Permissions', 'dollie' ),
				'name'              => 'wpd_client_site_permission',
				'type'              => 'radio',
				'instructions'      => __( 'Choose the user role given to the users when deploying a site. Warning, this will change the user roles for all client sites', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'choices'           => array(
					'administrator' => 'Administrator',
					'editor'        => 'Editor',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'default_value'     => 'administrator',
				'layout'            => 'vertical',
				'return_format'     => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key'               => 'field_5efc4ac9d5754',
				'label'             => __( 'Administrator User Name', 'dollie' ),
				'name'              => 'wpd_admin_user_name',
				'type'              => 'text',
				'instructions'      => __( 'Choose the username that is created for your own administration access. This won\'t be shared with the client.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5efc4a49d5752',
							'operator' => '==',
							'value'    => 'editor',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => 's_admin',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5b094d86fe6e8',
				'label'             => __( 'Blueprints', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5b097b1dd50cc',
				'label'             => __( 'Enable Site Preview', 'dollie' ),
				'name'              => 'wpd_enable_site_preview',
				'type'              => 'true_false',
				'instructions'      => __( 'The site preview bar allows you to quickly showcase the available Blueprints you\'ve created.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'message'           => '',
				'default_value'     => 1,
				'ui'                => 1,
				'ui_on_text'        => 'Yes',
				'ui_off_text'       => 'No',
			),
			array(
				'key'               => 'field_5b094db7fe6e9',
				'label'             => __( 'Site Preview Link', 'dollie' ),
				'name'              => 'wpd_site_preview_path',
				'type'              => 'text',
				'instructions'      => __( 'The link to where your sites preview will show. By default is set to "preview" and will look like your-site.com/preview', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5b097b1dd50cc',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => 'preview',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5fc8e845150e2',
				'label'             => __( 'Preview Page Logo', 'dollie' ),
				'name'              => 'wpd_dashboard_preview_logo',
				'type'              => 'image',
				'instructions'      => __( 'The link to where your sites preview will show. By default is set to "preview" and will look like your-site.com/preview', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5b097b1dd50cc',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'return_format'     => 'url',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5f561b0fc0227',
				'label'             => __( 'Show Default Blueprint', 'dollie' ),
				'name'              => 'wpd_show_default_blueprint',
				'type'              => 'true_false',
				'instructions'      => __( 'When launching a new site, show or hide the Default Blueprint option.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'message'           => '',
				'default_value'     => 1,
				'ui'                => 1,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'wpd_platform_setup',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5b0ea59dbbb22',
		'title'                 => 'Dollie Customer Data(do not edit)',
		'fields'                => array(
			array(
				'key'               => 'field_5b0ea5c46ffbb',
				'label'             => __( 'Active Dollie Subscription', 'dollie' ),
				'name'              => 'wpd_active_subscription',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5b0eaaa52ec57',
				'label'             => __( 'Stop Container at..', 'dollie' ),
				'name'              => 'wpd_stop_container_at',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5b0eacb73940a',
				'label'             => __( 'Containers undeployed?', 'dollie' ),
				'name'              => 'wpd_all_containers_undeployed',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'user_form',
					'operator' => '==',
					'value'    => 'edit',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5efc4bbc3849b',
		'title'                 => 'Dollie Customer Info',
		'fields'                => array(
			array(
				'key'               => 'field_5efc4bbc3d814',
				'label'             => __( 'Client Deployed Site Permissions', 'dollie' ),
				'name'              => 'wpd_client_site_permissions',
				'type'              => 'button_group',
				'instructions'      => __( 'Choose the user role given to the user when deploying a site. Default inherits from Dollie - Settings - Access Control', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'choices'           => array(
					'default'       => 'Default Dollie Setting',
					'administrator' => 'Administrator',
					'editor'        => 'Editor',
				),
				'allow_null'        => 0,
				'default_value'     => 'default',
				'layout'            => 'horizontal',
				'return_format'     => 'value',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'user_form',
					'operator' => '==',
					'value'    => 'edit',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5afc7b8e22840',
		'title'                 => 'Dollie Product Setup',
		'fields'                => array(
			array(
				'key'               => 'field_5e2c1a97c1541',
				'label'             => __( 'Basic', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5afc7bad022a8',
				'label'             => __( 'Number of Sites', 'dollie' ),
				'name'              => '_wpd_installs',
				'type'              => 'number',
				'instructions'      => __( 'How many sites can a customer deploy when subscribed to this product?', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => 1,
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'min'               => '',
				'max'               => '',
				'step'              => '',
			),
			array(
				'key'               => 'field_5afc7c0a022a9',
				'label'             => __( 'Disk Space', 'dollie' ),
				'name'              => '_wpd_max_size',
				'type'              => 'number',
				'instructions'      => __( 'The amount of space customer can use when subscribed to this product.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'hide_admin'        => 0,
				'default_value'     => '',
				'placeholder'       => 2,
				'prepend'           => '',
				'append'            => 'GB',
				'min'               => '',
				'max'               => '',
				'step'              => '',
			),
			array(
				'key'               => 'field_5e2c1ac7c1542',
				'label'             => __( 'Blueprints', 'dollie' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5e2c1adcc1543',
				'label'             => __( 'Included Blueprints', 'dollie' ),
				'name'              => '_wpd_included_blueprints',
				'type'              => 'relationship',
				'instructions'      => __( 'Select which of your Blueprints are allowed to be deployed when a customer has an active subscription to this product.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array(
					0 => 'container',
				),
				'taxonomy'          => '',
				'filters'           => '',
				'elements'          => '',
				'min'               => '',
				'max'               => '',
				'return_format'     => 'id',
			),
			array(
				'key'               => 'field_5e2c1b94c1544',
				'label'             => __( 'Excluded Blueprints', 'dollie' ),
				'name'              => '_wpd_excluded_blueprints',
				'type'              => 'relationship',
				'instructions'      => __( 'Select which of your Blueprints can not be chosen when a customer has an active subscription to this product. Use this setting if you have a lot of blueprints and only want to restrict access to a couple of them.', 'dollie' ),
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array(
					0 => 'container',
				),
				'taxonomy'          => '',
				'filters'           => '',
				'elements'          => '',
				'min'               => '',
				'max'               => '',
				'return_format'     => 'id',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'product',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

endif;
